Improve description of coordinate system
fontobene/fontobene pull request #35
Opened 2018-04-08 11:46 UTC by ubruhin

This very important thing was not really good explained until now...

2018-04-08 20:55 UTC, dbrgn requested changes

2018-04-08 20:55 UTC, dbrgn commented on SPECIFICATION.md
> +100% of the font height (i.e. the coordinate system is scaled with factor 9).
"Font height" is ambiguous. Maybe use the term "cap height"? See https://github.com/fontobene/fontobene/issues/5

We should probably also include that illustration in the spec. We have permission to do so.

2018-04-08 20:55 UTC, dbrgn commented on SPECIFICATION.md
> +Typical glyphs use the X axis (Y=0) as the baseline and are drawn inside the
I'd write "drawn mostly inside" instead of "drawn inside".

2018-04-08 20:55 UTC, dbrgn commented on SPECIFICATION.md
> +and descenders. And typical glyphs are left aligned to the Y axis (X=0).
I'd remove the "And".

2018-04-08 20:55 UTC, dbrgn commented on SPECIFICATION.md
> +Otherwise it influences letter spacing, see section "Letter Spacing" for details.
Maybe write "Glyphs that are not aligned to the Y axis have an impact on letter spacing, (...)" instead?

2018-04-08 20:56 UTC, dbrgn commented
By the way, would be great if the changes were detailed enough to be able to close #5.

2018-04-08 21:41 UTC, ubruhin commented
Added image and moved coordinate system specification to a separate section to not clutter up the polyline section too much -> [rendered](https://github.com/fontobene/fontobene/blob/40bf0ab74ba3efb1bf25f4b62c2c6fb86f44dd5b/SPECIFICATION.md)

2018-04-11 07:12 UTC, dbrgn approved these changes
Great, thanks! Feel free to merge if you think this is ready.

2018-04-11 17:23 UTC, merged