Add line spacing specifications and explanations
fontobene/fontobene pull request #36
Opened 2018-04-09 20:57 UTC by ubruhin

See #29 and #32.

2018-04-10 07:37 UTC, dbrgn requested changes
I'd really recommend changing the spacing definition from interline spacing to baseline-to-baseline, since that's how it's done in other systems (and in typography in general).

2018-04-10 07:37 UTC, dbrgn commented on SPECIFICATION.md
> +Line spacing is the vertical distance between the lines of a multiline text. It
Hm, that's not how line spacing is generally defined. Line spacing (aka leading) is usually baseline to baseline: https://en.wikipedia.org/wiki/Leading I'd stick with that.

2018-04-10 07:37 UTC, dbrgn commented on SPECIFICATION.md
> +can be defined with the `line_spacing` key in the header. The value basically
Can you replace "The value" with "A suitable value"?

2018-04-10 07:37 UTC, dbrgn commented on SPECIFICATION.md
> +height. For a typical font this may be around 7 (78% of font height).
If we define the line spacing as baseline to baseline, then we would have to adjust this wording.

From Wikipedia (linked above):

> In both cases, with a 10 pt font the usual leading is 12 pt, creating a 10/12 ratio, which is considered single spacing. Some type designers recommend a leading between 120% and 145% of the font size.

So we could recommend values between 10.8 and 12.6.

2018-04-10 19:37 UTC, ubruhin commented
Thanks for reviewing @dbrgn!

> I'd really recommend changing the spacing definition from interline spacing to baseline-to-baseline

Actually I had it defined like that in the first version, but then I had the idea to define it the same way as letter spacing (for consistency) and because the default value for `line_spacing` would be 0 instead of 9 :sob: 

-> Changed back to baseline distance. OK now?

2018-04-10 19:43 UTC, ubruhin commented
> So we could recommend values between 10.8 and 12.6.

That would be far too less. In the Wikipedia article they have another definition for font height (=100%). It seems they count descenders to the font height, which we don't. So with our definition of font height we need much more space. With the "unicode" font I've tested, 178% line distance is fine.

2018-04-11 07:20 UTC, dbrgn approved these changes
Two small wording improvements, otherwise good to merge in my opinion :slightly_smiling_face: Thanks!

2018-04-11 07:20 UTC, dbrgn commented on SPECIFICATION.md
> +basically depends on the height of ascenders and descenders to avoid vertically
Can you remove "basically"? It doesn't add any value.

2018-04-11 07:20 UTC, dbrgn commented on SPECIFICATION.md
> +slightly greater than the addition of the cap height (9), highest ascender and
I'd append "height" to the ascender. Yes, it's a repetition, but it's a spec so it's better to stick to more formal language :)

2018-04-11 17:21 UTC, merged