Add very simple example
fontobene/fontobene pull request #38
Opened 2018-04-11 21:31 UTC by dbrgn

Fixes #16.

I noticed that whitespace inheritance might be a bit confusing. If you have an "I" character with whitespace and a "_" character without any whitespace, and you inherit from both to form the "L" character, then the "L" *will* have whitespace, but following the glyph, not in the middle. If the "_" would specify 0 whitespace, then the "L" will not have any whitespace following it.

It's not wrong by any means, but can get a bit complex.

2018-04-11 21:50 UTC, ubruhin commented
I would strongly suggest to make the example as realistic as possible. Currently I don't consider it as realistic because of two reasons:
- `letter_spacing` and `line_spacing` are not defined in the header. So all glyphs without additional whitespace will touch each other, which doesn't make sense.
- 5 of 6 glyphs have additional whitespace defined. This suggests that additional whitespace is used very often (e.g. after a sans serif "i"), which is simply not true. I would remove all whitespace definitions, except from U+0020 (yes, even if then the example with whitespace inheritance/override would be removed - but most fonts will probably never use these features anyway).

2018-04-11 21:55 UTC, dbrgn commented
The goal was not to make it realistic (for that we have actual fonts). The goal was to demonstrate the different features in as few glyphs as possible (e.g. inheritance to form new characters, circular arc segments to form the "B" or cancelling out whitespace).

As soon as we have a font directory, we can link to that.

2018-04-11 22:02 UTC, ubruhin commented
Hmm OK. But yes then I would like to see a note that that's not a realistic example and

> As soon as we have a font directory, we can link to that.

2018-04-15 22:43 UTC, dbrgn commented
@ubruhin better?

2018-04-16 21:30 UTC, ubruhin requested changes

2018-04-16 21:30 UTC, ubruhin commented on SPECIFICATION.md
> +## Example
Now this chapter needs a TOC entry :)

2018-04-17 20:54 UTC, dbrgn commented on SPECIFICATION.md
> +## Example
Done

2018-04-17 22:03 UTC, ubruhin approved these changes

2018-04-17 22:35 UTC, merged